# Generated by Django 4.1.7 on 2023-04-01 19:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_followerscount"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostComment",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("timestamp", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.postcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
