# Generated by Django 4.1.7 on 2023-04-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_postcomment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostComment",
        ),
    ]
